"""initial schema

Revision ID: e8eaecc5aad2
Revises: 
Create Date: 2026-06-22 21:28:07.884223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8eaecc5aad2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deductible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage_percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('annual_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('annual_limit >= 0', name='ck_policy_annual_limit_non_negative'),
    sa.CheckConstraint('coverage_percentage >= 0 AND coverage_percentage <= 1', name='ck_policy_coverage_percentage_range'),
    sa.CheckConstraint('deductible >= 0', name='ck_policy_deductible_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_rules',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_covered', sa.Boolean(), nullable=False),
    sa.Column('coverage_percentage_override', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('coverage_percentage_override IS NULL OR (coverage_percentage_override >= 0 AND coverage_percentage_override <= 1)', name='ck_coverage_rule_override_range'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'service_code', name='uq_coverage_rule_policy_service')
    )
    with op.batch_alter_table('coverage_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_rules_policy_id'), ['policy_id'], unique=False)

    op.create_table('members',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('deductible_met', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('amount_paid_ytd', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_paid_ytd >= 0', name='ck_member_amount_paid_ytd_non_negative'),
    sa.CheckConstraint('deductible_met >= 0', name='ck_member_deductible_met_non_negative'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_policy_id'), ['policy_id'], unique=False)

    op.create_table('claims',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_service', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'PARTIALLY_APPROVED', 'DENIED', 'PAID', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('adjudicated_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_member_id'), ['member_id'], unique=False)

    op.create_table('claim_line_items',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('service_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('billed_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='claimlineitemstatus', native_enum=False), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('approved_amount IS NULL OR approved_amount >= 0', name='ck_line_item_approved_amount_non_negative'),
    sa.CheckConstraint('billed_amount >= 0', name='ck_line_item_billed_amount_non_negative'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_line_items_claim_id'), ['claim_id'], unique=False)

    op.create_table('disputes',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'REJECTED', name='disputestatus', native_enum=False), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_claim_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('claim_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_line_items_claim_id'))

    op.drop_table('claim_line_items')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_member_id'))

    op.drop_table('claims')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_policy_id'))

    op.drop_table('members')
    with op.batch_alter_table('coverage_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_rules_policy_id'))

    op.drop_table('coverage_rules')
    op.drop_table('policies')
    # ### end Alembic commands ###
